import type { Character, Question } from './types'

export const DEFAULT_CHARACTERS: Character[] = [
  {
    id: 'mario',
    name: 'Mario',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'pikachu',
    name: 'Pikachu',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'darth-vader',
    name: 'Darth Vader',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
    },
  },
  {
    id: 'harry-potter',
    name: 'Harry Potter',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'sherlock-holmes',
    name: 'Sherlock Holmes',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'superman',
    name: 'Superman',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'gandalf',
    name: 'Gandalf',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'spongebob',
    name: 'SpongeBob SquarePants',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'batman',
    name: 'Batman',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'sonic',
    name: 'Sonic the Hedgehog',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'yoda',
    name: 'Yoda',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'joker',
    name: 'The Joker',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: false,
      canTalk: true,
    },
  },
  {
    id: 'smaug',
    name: 'Smaug',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: true,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
    },
  },
  {
    id: 'wall-e',
    name: 'WALL-E',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: false,
    },
  },
  {
    id: 'hermione',
    name: 'Hermione Granger',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'godzilla',
    name: 'Godzilla',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: null,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: null,
      canTalk: false,
    },
  },
  {
    id: 'elsa',
    name: 'Elsa',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'link',
    name: 'Link',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: false,
      isHero: true,
      canTalk: false,
    },
  },
  {
    id: 'totoro',
    name: 'Totoro',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: false,
    },
  },
  {
    id: 'r2d2',
    name: 'R2-D2',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: false,
    },
  },
  {
    id: 'voldemort',
    name: 'Voldemort',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: false,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
    },
  },
  {
    id: 'lara-croft',
    name: 'Lara Croft',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'groot',
    name: 'Groot',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'maleficent',
    name: 'Maleficent',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
    },
  },
  {
    id: 'kratos',
    name: 'Kratos',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'stitch',
    name: 'Stitch',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'bowser',
    name: 'Bowser',
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
    },
  },
  {
    id: 'iron-man',
    name: 'Iron Man',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'shrek',
    name: 'Shrek',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'baymax',
    name: 'Baymax',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
    },
  },
  {
    id: 'thanos',
    name: 'Thanos',
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
    },
  },
]

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: 'q1',
    text: 'Is this character from a video game?',
    attribute: 'fromVideoGame',
  },
  {
    id: 'q2',
    text: 'Is this character a villain or antagonist?',
    attribute: 'isVillain',
  },
  {
    id: 'q3',
    text: 'Does this character have superpowers?',
    attribute: 'hasSuperpowers',
  },
  {
    id: 'q4',
    text: 'Is this character an animal or creature?',
    attribute: 'isAnimal',
  },
  {
    id: 'q5',
    text: 'Can this character fly?',
    attribute: 'canFly',
  },
  {
    id: 'q6',
    text: 'Does this character wear a hat?',
    attribute: 'wearsHat',
  },
  {
    id: 'q7',
    text: 'Does this character have magic powers?',
    attribute: 'hasMagicPowers',
  },
  {
    id: 'q8',
    text: 'Is this character from a movie?',
    attribute: 'fromMovie',
  },
  {
    id: 'q9',
    text: 'Is this character from a book originally?',
    attribute: 'fromBook',
  },
  {
    id: 'q10',
    text: 'Is this character a human?',
    attribute: 'isHuman',
  },
  {
    id: 'q11',
    text: 'Is this character considered a hero?',
    attribute: 'isHero',
  },
  {
    id: 'q12',
    text: 'Can this character speak/talk?',
    attribute: 'canTalk',
  },
]
