import type { Character, Question } from "./types";

export const DEFAULT_CHARACTERS: Character[] = [
  {
    id: "mario",
    name: "Mario",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: true,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "pikachu",
    name: "Pikachu",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: null,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "darth-vader",
    name: "Darth Vader",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: true,
      livesInCity: false,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "harry-potter",
    name: "Harry Potter",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: true,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: true,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: true,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: true,
      hasPet: true,
      isRoyalty: false,
    },
  },
  {
    id: "sherlock-holmes",
    name: "Sherlock Holmes",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "superman",
    name: "Superman",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: true,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: true,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "gandalf",
    name: "Gandalf",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: true,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: true,
      isLeader: true,
      canTeleport: true,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "spongebob",
    name: "SpongeBob SquarePants",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: true,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: false,
    },
  },
  {
    id: "batman",
    name: "Batman",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "sonic",
    name: "Sonic the Hedgehog",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "yoda",
    name: "Yoda",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: true,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "joker",
    name: "The Joker",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: false,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: true,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "smaug",
    name: "Smaug",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: true,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "wall-e",
    name: "WALL-E",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: false,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: true,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: true,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "hermione",
    name: "Hermione Granger",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: true,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: true,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: true,
      hasPet: true,
      isRoyalty: false,
    },
  },
  {
    id: "godzilla",
    name: "Godzilla",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: null,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: null,
      canTalk: false,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: null,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: true,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "elsa",
    name: "Elsa",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: true,
    },
  },
  {
    id: "link",
    name: "Link",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: false,
      isHero: true,
      canTalk: false,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: true,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: true,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "totoro",
    name: "Totoro",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: false,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: null,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: true,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: true,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: true,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "r2d2",
    name: "R2-D2",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: false,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: true,
      hasCompanion: true,
      isMale: null,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: true,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "voldemort",
    name: "Voldemort",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: false,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: true,
      hasFamily: false,
      isImmortal: true,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: true,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: false,
    },
  },
  {
    id: "lara-croft",
    name: "Lara Croft",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: false,
      isMale: false,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: true,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "groot",
    name: "Groot",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: true,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: true,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "maleficent",
    name: "Maleficent",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: true,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: true,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: false,
    },
  },
  {
    id: "kratos",
    name: "Kratos",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: true,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: true,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "stitch",
    name: "Stitch",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: true,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: true,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "bowser",
    name: "Bowser",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: true,
    },
  },
  {
    id: "iron-man",
    name: "Iron Man",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: true,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: true,
      livesInCity: true,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "shrek",
    name: "Shrek",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "baymax",
    name: "Baymax",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: true,
      hasCompanion: true,
      isMale: null,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: true,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
    },
  },
  {
    id: "thanos",
    name: "Thanos",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: true,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: false,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: true,
      isFunny: false,
      fromSpace: true,
      livesInCity: false,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: true,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "spider-man",
    name: "Spider-Man",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: true,
      climbsWalls: true,
      hasSpiderSense: true,
      livesInNewYork: true,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "wolverine",
    name: "Wolverine",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: true,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: true,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: true,
      hasClaws: true,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "doctor-octopus",
    name: "Doctor Octopus",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: true,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: false,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: false,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: true,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: true,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: true,
      hasSpiderSense: false,
      livesInNewYork: true,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: true,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "cyclops",
    name: "Cyclops",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: true,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: true,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: true,
      controlsWeather: false,
    },
  },
  {
    id: "storm",
    name: "Storm",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: true,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: true,
    },
  },
  {
    id: "hawkman",
    name: "Hawkman",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: true,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: true,
      livesInCity: true,
      canSwim: false,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: true,
      hasWings: true,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "buzz-lightyear",
    name: "Buzz Lightyear",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: true,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: true,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: true,
      controlsWeather: false,
    },
  },
  {
    id: "woody",
    name: "Woody",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: true,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "simba",
    name: "Simba",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: true,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "nemo",
    name: "Nemo",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: true,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "rapunzel",
    name: "Rapunzel",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "moana",
    name: "Moana",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "goku",
    name: "Goku",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: true,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: true,
      isFunny: true,
      fromSpace: true,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: true,
      controlsWeather: false,
    },
  },
  {
    id: "naruto",
    name: "Naruto",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: true,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: true,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "sailor-moon",
    name: "Sailor Moon",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: true,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: true,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: true,
      controlsWeather: false,
    },
  },
  {
    id: "master-chief",
    name: "Master Chief",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: true,
      livesInCity: false,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "pac-man",
    name: "Pac-Man",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: false,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "princess-peach",
    name: "Princess Peach",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "donkey-kong",
    name: "Donkey Kong",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: true,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "mega-man",
    name: "Mega Man",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: false,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: true,
      hasCompanion: true,
      isMale: true,
      canShapeshift: true,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: true,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: false,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: true,
      controlsWeather: false,
    },
  },
  {
    id: "wonder-woman",
    name: "Wonder Woman",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: true,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "the-flash",
    name: "The Flash",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: true,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "hulk",
    name: "Hulk",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: true,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: true,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "captain-america",
    name: "Captain America",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: true,
      usesTechnology: true,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: true,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: true,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "thor",
    name: "Thor",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: false,
      canFly: true,
      hasSuperpowers: true,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: true,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: true,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: true,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: true,
      livesInCity: false,
      canSwim: true,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: true,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: true,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: true,
      hasTentacles: false,
      shootsLasers: true,
      controlsWeather: true,
    },
  },
  {
    id: "mickey-mouse",
    name: "Mickey Mouse",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: true,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: true,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "bugs-bunny",
    name: "Bugs Bunny",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "scooby-doo",
    name: "Scooby-Doo",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: false,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: true,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "katniss",
    name: "Katniss Everdeen",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: false,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "mulan",
    name: "Mulan",
    attributes: {
      isReal: false,
      isAnimal: false,
      isHuman: true,
      canFly: false,
      hasSuperpowers: false,
      isVillain: false,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: true,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: true,
      canTalk: true,
      hasWeapon: true,
      usesVehicle: true,
      isRobot: false,
      hasCompanion: true,
      isMale: false,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: false,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: true,
      hasArmor: true,
      usesTechnology: false,
      wearsCape: false,
      hasTail: false,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: true,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: true,
      isRoyalty: false,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: false,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
  {
    id: "scar",
    name: "Scar",
    attributes: {
      isReal: false,
      isAnimal: true,
      isHuman: false,
      canFly: false,
      hasSuperpowers: false,
      isVillain: true,
      fromVideoGame: false,
      fromMovie: true,
      fromBook: false,
      isFictional: true,
      wearsHat: false,
      hasMagicPowers: false,
      isHero: false,
      canTalk: true,
      hasWeapon: false,
      usesVehicle: false,
      isRobot: false,
      hasCompanion: true,
      isMale: true,
      canShapeshift: false,
      hasFamily: true,
      isImmortal: false,
      hasJob: true,
      wearsGlasses: false,
      hasFacialHair: false,
      isLeader: true,
      canTeleport: false,
      isFunny: false,
      fromSpace: false,
      livesInCity: false,
      canSwim: false,
      hasArmor: false,
      usesTechnology: false,
      wearsCape: false,
      hasTail: true,
      canBreatheUnderwater: false,
      isInvisible: false,
      hasSidekick: false,
      wearsMask: false,
      canControlElements: false,
      canTimeTravel: false,
      hasPet: false,
      isRoyalty: true,
      hasWebShooters: false,
      climbsWalls: false,
      hasSpiderSense: false,
      livesInNewYork: false,
      hasClaws: true,
      hasWings: false,
      canRegenerate: false,
      hasTentacles: false,
      shootsLasers: false,
      controlsWeather: false,
    },
  },
];

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: "q1",
    text: "Is this character from a video game?",
    attribute: "fromVideoGame",
  },
  {
    id: "q2",
    text: "Is this character a villain or antagonist?",
    attribute: "isVillain",
  },
  {
    id: "q3",
    text: "Does this character have superpowers?",
    attribute: "hasSuperpowers",
  },
  {
    id: "q4",
    text: "Is this character an animal or creature?",
    attribute: "isAnimal",
  },
  {
    id: "q5",
    text: "Can this character fly?",
    attribute: "canFly",
  },
  {
    id: "q6",
    text: "Does this character wear a hat?",
    attribute: "wearsHat",
  },
  {
    id: "q7",
    text: "Does this character have magic powers?",
    attribute: "hasMagicPowers",
  },
  {
    id: "q8",
    text: "Is this character from a movie?",
    attribute: "fromMovie",
  },
  {
    id: "q9",
    text: "Is this character from a book originally?",
    attribute: "fromBook",
  },
  {
    id: "q10",
    text: "Is this character a human?",
    attribute: "isHuman",
  },
  {
    id: "q11",
    text: "Is this character considered a hero?",
    attribute: "isHero",
  },
  {
    id: "q12",
    text: "Can this character speak/talk?",
    attribute: "canTalk",
  },
  {
    id: "q13",
    text: "Does this character use or carry a weapon?",
    attribute: "hasWeapon",
  },
  {
    id: "q14",
    text: "Does this character use or drive vehicles?",
    attribute: "usesVehicle",
  },
  {
    id: "q15",
    text: "Is this character a robot or machine?",
    attribute: "isRobot",
  },
  {
    id: "q16",
    text: "Does this character have a close companion or partner?",
    attribute: "hasCompanion",
  },
  {
    id: "q17",
    text: "Is this character male?",
    attribute: "isMale",
  },
  {
    id: "q18",
    text: "Can this character shapeshift or transform?",
    attribute: "canShapeshift",
  },
  {
    id: "q19",
    text: "Does this character have family members that are important to their story?",
    attribute: "hasFamily",
  },
  {
    id: "q20",
    text: "Is this character immortal or extremely long-lived?",
    attribute: "isImmortal",
  },
  {
    id: "q21",
    text: "Does this character have a specific job or profession?",
    attribute: "hasJob",
  },
  {
    id: "q22",
    text: "Does this character wear glasses?",
    attribute: "wearsGlasses",
  },
  {
    id: "q23",
    text: "Does this character have facial hair (beard, mustache)?",
    attribute: "hasFacialHair",
  },
  {
    id: "q24",
    text: "Is this character a leader of a group or team?",
    attribute: "isLeader",
  },
  {
    id: "q25",
    text: "Can this character teleport?",
    attribute: "canTeleport",
  },
  {
    id: "q26",
    text: "Is this character particularly funny or comedic?",
    attribute: "isFunny",
  },
  {
    id: "q27",
    text: "Is this character from outer space or another planet?",
    attribute: "fromSpace",
  },
  {
    id: "q28",
    text: "Does this character live in a city?",
    attribute: "livesInCity",
  },
  {
    id: "q29",
    text: "Can this character swim?",
    attribute: "canSwim",
  },
  {
    id: "q30",
    text: "Does this character wear armor?",
    attribute: "hasArmor",
  },
  {
    id: "q31",
    text: "Does this character use advanced technology regularly?",
    attribute: "usesTechnology",
  },
  {
    id: "q32",
    text: "Does this character wear a cape?",
    attribute: "wearsCape",
  },
  {
    id: "q33",
    text: "Does this character have a tail?",
    attribute: "hasTail",
  },
  {
    id: "q34",
    text: "Can this character breathe underwater?",
    attribute: "canBreatheUnderwater",
  },
  {
    id: "q35",
    text: "Can this character become invisible?",
    attribute: "isInvisible",
  },
  {
    id: "q36",
    text: "Does this character have a sidekick?",
    attribute: "hasSidekick",
  },
  {
    id: "q37",
    text: "Does this character wear a mask?",
    attribute: "wearsMask",
  },
  {
    id: "q38",
    text: "Can this character control elements (fire, water, ice, etc.)?",
    attribute: "canControlElements",
  },
  {
    id: "q39",
    text: "Can this character time travel?",
    attribute: "canTimeTravel",
  },
  {
    id: "q40",
    text: "Does this character have a pet or animal companion?",
    attribute: "hasPet",
  },
  {
    id: "q41",
    text: "Is this character royalty (king, queen, prince, princess)?",
    attribute: "isRoyalty",
  },
  {
    id: "q42",
    text: "Does this character have web shooters?",
    attribute: "hasWebShooters",
  },
  {
    id: "q43",
    text: "Can this character climb walls or stick to surfaces?",
    attribute: "climbsWalls",
  },
  {
    id: "q44",
    text: "Does this character have a spider sense or danger detection ability?",
    attribute: "hasSpiderSense",
  },
  {
    id: "q45",
    text: "Does this character live in New York City?",
    attribute: "livesInNewYork",
  },
  {
    id: "q46",
    text: "Does this character have claws?",
    attribute: "hasClaws",
  },
  {
    id: "q47",
    text: "Does this character have wings?",
    attribute: "hasWings",
  },
  {
    id: "q48",
    text: "Can this character regenerate or heal quickly?",
    attribute: "canRegenerate",
  },
  {
    id: "q49",
    text: "Does this character have tentacles?",
    attribute: "hasTentacles",
  },
  {
    id: "q50",
    text: "Can this character shoot lasers or energy beams from their eyes?",
    attribute: "shootsLasers",
  },
  {
    id: "q51",
    text: "Can this character control the weather?",
    attribute: "controlsWeather",
  },
];
