-- ============================================================
-- Phase 2: Expanded attribute taxonomy
-- Generated: 2026-04-18T21:33:45.788Z
-- New attributes: 171
-- ============================================================

-- New attribute definitions
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isProtagonist', 'Protagonist', 'Is this character the protagonist?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isAntagonist', 'Antagonist', 'Is this character the antagonist?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasRedHair', 'Red Hair', 'Does this character have red hair?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromJapan', 'From Japan', 'Is this character from Japan?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasGreenEyes', 'Green Eyes', 'Does this character have green eyes?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isTeenager', 'Teenager', 'Is this character a teenager?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isMentor', 'Mentor', 'Is this character a mentor?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isSidekick', 'Sidekick', 'Is this character a sidekick?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasScar', 'Scar', 'Does this character have a scar?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasTattoos', 'Tattoos', 'Does this character have tattoos?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isPirate', 'Pirate', 'Is this character a pirate?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isNinja', 'Ninja', 'Is this character a ninja?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isSamurai', 'Samurai', 'Is this character a samurai?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isDetective', 'Detective', 'Is this character a detective?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('livesInSpace', 'Lives in Space', 'Does this character live in space?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasSuperSpeed', 'Super Speed', 'Does this character have super speed?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canReadMinds', 'Mind Reading', 'Can this character read minds?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canBecomeGiant', 'Can Become Giant', 'Can this character become giant?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isAlien', 'Alien', 'Is this character an alien?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasGlasses', 'Glasses', 'Does this character wear glasses?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isCyborg', 'Cyborg', 'Is this character a cyborg?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isKnight', 'Knight', 'Is this character a knight?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isScientist', 'Scientist', 'Is this character a scientist?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isWizard', 'Wizard', 'Is this character a wizard?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isAssassin', 'Assassin', 'Is this character an assassin?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isEngineer', 'Engineer', 'Is this character an engineer?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromFantasyWorld', 'From Fantasy World', 'Is this character from a fantasy world?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromEarth', 'From Earth', 'Is this character from Earth?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasBlondeHair', 'Blonde Hair', 'Does this character have blonde hair?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasBlueEyes', 'Blue Eyes', 'Does this character have blue eyes?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasFreckles', 'Freckles', 'Does this character have freckles?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasBeard', 'Beard', 'Does this character have a beard?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isVampire', 'Vampire', 'Is this character a vampire?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isZombie', 'Zombie', 'Is this character a zombie?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isGhost', 'Ghost', 'Is this character a ghost?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isGod', 'God', 'Is this character a god or deity?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isDemon', 'Demon', 'Is this character a demon?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isElf', 'Elf', 'Is this character an elf?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isDwarf', 'Dwarf', 'Is this character a dwarf?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isGiant', 'Giant', 'Is this character a giant?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isOrc', 'Orc', 'Is this character an orc?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isGreedy', 'Greedy', 'Is this character greedy?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isBrave', 'Brave', 'Is this character brave?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isCowardly', 'Cowardly', 'Is this character cowardly?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isKind', 'Kind', 'Is this character kind?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isCruel', 'Cruel', 'Is this character cruel?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isIntelligent', 'Intelligent', 'Is this character intelligent?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFoolish', 'Foolish', 'Is this character foolish?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isRebellious', 'Rebellious', 'Is this character rebellious?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isLoyal', 'Loyal', 'Is this character loyal?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isTraitor', 'Traitor', 'Is this character a traitor?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isCharming', 'Charming', 'Is this character charming?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isClumsy', 'Clumsy', 'Is this character clumsy?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isSarcastic', 'Sarcastic', 'Is this character sarcastic?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isNaive', 'Naive', 'Is this character naive?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isWise', 'Wise', 'Is this character wise?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isSkeptical', 'Skeptical', 'Is this character skeptical?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isOptimistic', 'Optimistic', 'Is this character optimistic?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isPessimistic', 'Pessimistic', 'Is this character pessimistic?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isCurious', 'Curious', 'Is this character curious?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isCunning', 'Cunning', 'Is this character cunning?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isHonest', 'Honest', 'Is this character honest?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isDevious', 'Devious', 'Is this character devious?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isHumorous', 'Humorous', 'Is this character humorous?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isSerious', 'Serious', 'Is this character serious?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isAdventurous', 'Adventurous', 'Is this character adventurous?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isCreative', 'Creative', 'Is this character creative?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isLazy', 'Lazy', 'Is this character lazy?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isEnergetic', 'Energetic', 'Is this character energetic?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isPatient', 'Patient', 'Is this character patient?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isImpatient', 'Impatient', 'Is this character impatient?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isRich', 'Rich', 'Is this character rich?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isPoor', 'Poor', 'Is this character poor?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasSuperStrength', 'Super Strength', 'Does this character have super strength?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canTurnInvisible', 'Invisibility', 'Can this character turn invisible?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canControlTime', 'Time Control', 'Can this character control time?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canCreateIllusions', 'Illusion Creation', 'Can this character create illusions?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canTalkToAnimals', 'Animal Communication', 'Can this character talk to animals?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canGenerateElectricity', 'Electricity Generation', 'Can this character generate electricity?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('canWalkThroughWalls', 'Wall Phasing', 'Can this character walk through walls?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasLongHair', 'Long Hair', 'Does this character have long hair?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasShortHair', 'Short Hair', 'Does this character have short hair?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isBald', 'Bald', 'Is this character bald?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasRobotCompanion', 'Robot Companion', 'Does this character have a robot companion?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasAnimalCompanion', 'Animal Companion', 'Does this character have an animal companion?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasSibling', 'Sibling', 'Does this character have a sibling?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isMarried', 'Married', 'Is this character married?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isSingle', 'Single', 'Is this character single?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasChildren', 'Children', 'Does this character have children?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromModernEra', 'From Modern Era', 'Is this character from the modern era?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMedievalTimes', 'From Medieval Times', 'Is this character from medieval times?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromFuture', 'From Future', 'Is this character from the future?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('appearsInSequel', 'Appears in Sequel', 'Does this character appear in a sequel?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('appearsInPrequel', 'Appears in Prequel', 'Does this character appear in a prequel?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isIconic', 'Iconic', 'Is this character considered iconic?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasThemeSong', 'Theme Song', 'Does this character have a theme song?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isPartOfFranchise', 'Part of Franchise', 'Is this character part of a franchise?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromIndieSource', 'From Indie Source', 'Is this character from an indie source?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isBasedOnRealPerson', 'Based on Real Person', 'Is this character based on a real person?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromHistoricalFiction', 'From Historical Fiction', 'Is this character from historical fiction?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasCatchphrase', 'Catchphrase', 'Does this character have a catchphrase?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isPartOfEnsembleCast', 'Part of Ensemble Cast', 'Is this character part of an ensemble cast?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromAnimatedSeries', 'From Animated Series', 'Is this character from an animated series?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromLiveAction', 'From Live Action', 'Is this character from a live-action production?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromSuperheroGenre', 'From Superhero Genre', 'Is this character from the superhero genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromHorrorGenre', 'From Horror Genre', 'Is this character from the horror genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromComedyGenre', 'From Comedy Genre', 'Is this character from the comedy genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromDramaGenre', 'From Drama Genre', 'Is this character from the drama genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromRomanceGenre', 'From Romance Genre', 'Is this character from the romance genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromSciFiGenre', 'From Sci-Fi Genre', 'Is this character from the science fiction genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromFantasyGenre', 'From Fantasy Genre', 'Is this character from the fantasy genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMysteryGenre', 'From Mystery Genre', 'Is this character from the mystery genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromActionGenre', 'From Action Genre', 'Is this character from the action genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromThrillerGenre', 'From Thriller Genre', 'Is this character from the thriller genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromWesternGenre', 'From Western Genre', 'Is this character from the western genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMusicalGenre', 'From Musical Genre', 'Is this character from the musical genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromDocumentary', 'From Documentary', 'Is this character from a documentary?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromAdventureGenre', 'From Adventure Genre', 'Is this character from the adventure genre?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromGameShow', 'From Game Show', 'Is this character from a game show?', '["tv-shows"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isVideoGameCharacter', 'Video Game Character', 'Is this character from a video game?', '["video-games"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromComicBook', 'From Comic Book', 'Is this character from a comic book?', '["comics"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromAnime', 'From Anime', 'Is this character from an anime?', '["anime"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromCartoon', 'From Cartoon', 'Is this character from a cartoon?', '["cartoons"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromTVShow', 'From TV Show', 'Is this character from a TV show?', '["tv-shows"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMovie', 'From Movie', 'Is this character from a movie?', '["movies"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromBook', 'From Book', 'Is this character from a book?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromPopCulture', 'From Pop Culture', 'Is this character from pop culture?', '["pop-culture"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromSitcom', 'From Sitcom', 'Is this character from a sitcom?', '["tv-shows"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromRealityShow', 'From Reality Show', 'Is this character from a reality show?', '["tv-shows"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromFantasyNovel', 'From Fantasy Novel', 'Is this character from a fantasy novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromSciFiNovel', 'From Sci-Fi Novel', 'Is this character from a sci-fi novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMysteryNovel', 'From Mystery Novel', 'Is this character from a mystery novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromThrillerNovel', 'From Thriller Novel', 'Is this character from a thriller novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromRomanceNovel', 'From Romance Novel', 'Is this character from a romance novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromHorrorNovel', 'From Horror Novel', 'Is this character from a horror novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromHistoricalNovel', 'From Historical Novel', 'Is this character from a historical novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromAdventureNovel', 'From Adventure Novel', 'Is this character from an adventure novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromActionNovel', 'From Action Novel', 'Is this character from an action novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromWesternNovel', 'From Western Novel', 'Is this character from a western novel?', '["books"]');
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFemale', 'Female', 'Is this character female?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isNonBinary', 'Non-Binary', 'Is this character non-binary?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isGenderFluid', 'Gender Fluid', 'Is this character gender fluid?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isTransgender', 'Transgender', 'Is this character transgender?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromRoyalFamily', 'From Royal Family', 'Is this character from a royal family?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMilitary', 'From Military', 'Is this character from the military?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromNobleFamily', 'From Noble Family', 'Is this character from a noble family?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromWealthyFamily', 'From Wealthy Family', 'Is this character from a wealthy family?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromPoorFamily', 'From Poor Family', 'Is this character from a poor family?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMiddleClass', 'From Middle Class', 'Is this character from the middle class?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromCountryside', 'From Countryside', 'Is this character from the countryside?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromCity', 'From City', 'Is this character from the city?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromSmallTown', 'From Small Town', 'Is this character from a small town?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromIsland', 'From Island', 'Is this character from an island?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromJungle', 'From Jungle', 'Is this character from the jungle?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromDesert', 'From Desert', 'Is this character from the desert?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromMountains', 'From Mountains', 'Is this character from the mountains?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromUnderground', 'From Underground', 'Is this character from an underground setting?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromOcean', 'From Ocean', 'Is this character from the ocean?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromForest', 'From Forest', 'Is this character from the forest?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromSwamp', 'From Swamp', 'Is this character from the swamp?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromCastle', 'From Castle', 'Is this character from a castle?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromVillage', 'From Village', 'Is this character from a village?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromUtopia', 'From Utopia', 'Is this character from a utopia?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isFromDystopia', 'From Dystopia', 'Is this character from a dystopia?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('hasAccent', 'Accent', 'Does this character have an accent?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isMute', 'Mute', 'Is this character mute?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isDeaf', 'Deaf', 'Is this character deaf?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isBlind', 'Blind', 'Is this character blind?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isDisabled', 'Disabled', 'Is this character disabled?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isSupernatural', 'Supernatural', 'Is this character supernatural?', NULL);
INSERT INTO attribute_definitions (key, display_text, question_text, categories) VALUES ('isMythical', 'Mythical', 'Is this character mythical?', NULL);

-- New questions for expanded attributes
INSERT INTO questions (id, text, attribute_key) VALUES ('q52', 'Is this character the protagonist?', 'isProtagonist');
INSERT INTO questions (id, text, attribute_key) VALUES ('q53', 'Is this character the antagonist?', 'isAntagonist');
INSERT INTO questions (id, text, attribute_key) VALUES ('q54', 'Does this character have red hair?', 'hasRedHair');
INSERT INTO questions (id, text, attribute_key) VALUES ('q55', 'Is this character from Japan?', 'isFromJapan');
INSERT INTO questions (id, text, attribute_key) VALUES ('q56', 'Does this character have green eyes?', 'hasGreenEyes');
INSERT INTO questions (id, text, attribute_key) VALUES ('q57', 'Is this character a teenager?', 'isTeenager');
INSERT INTO questions (id, text, attribute_key) VALUES ('q58', 'Is this character a mentor?', 'isMentor');
INSERT INTO questions (id, text, attribute_key) VALUES ('q59', 'Is this character a sidekick?', 'isSidekick');
INSERT INTO questions (id, text, attribute_key) VALUES ('q60', 'Does this character have a scar?', 'hasScar');
INSERT INTO questions (id, text, attribute_key) VALUES ('q61', 'Does this character have tattoos?', 'hasTattoos');
INSERT INTO questions (id, text, attribute_key) VALUES ('q62', 'Is this character a pirate?', 'isPirate');
INSERT INTO questions (id, text, attribute_key) VALUES ('q63', 'Is this character a ninja?', 'isNinja');
INSERT INTO questions (id, text, attribute_key) VALUES ('q64', 'Is this character a samurai?', 'isSamurai');
INSERT INTO questions (id, text, attribute_key) VALUES ('q65', 'Is this character a detective?', 'isDetective');
INSERT INTO questions (id, text, attribute_key) VALUES ('q66', 'Does this character live in space?', 'livesInSpace');
INSERT INTO questions (id, text, attribute_key) VALUES ('q67', 'Does this character have super speed?', 'hasSuperSpeed');
INSERT INTO questions (id, text, attribute_key) VALUES ('q68', 'Can this character read minds?', 'canReadMinds');
INSERT INTO questions (id, text, attribute_key) VALUES ('q69', 'Can this character become giant?', 'canBecomeGiant');
INSERT INTO questions (id, text, attribute_key) VALUES ('q70', 'Is this character an alien?', 'isAlien');
INSERT INTO questions (id, text, attribute_key) VALUES ('q71', 'Does this character wear glasses?', 'hasGlasses');
INSERT INTO questions (id, text, attribute_key) VALUES ('q72', 'Is this character a cyborg?', 'isCyborg');
INSERT INTO questions (id, text, attribute_key) VALUES ('q73', 'Is this character a knight?', 'isKnight');
INSERT INTO questions (id, text, attribute_key) VALUES ('q74', 'Is this character a scientist?', 'isScientist');
INSERT INTO questions (id, text, attribute_key) VALUES ('q75', 'Is this character a wizard?', 'isWizard');
INSERT INTO questions (id, text, attribute_key) VALUES ('q76', 'Is this character an assassin?', 'isAssassin');
INSERT INTO questions (id, text, attribute_key) VALUES ('q77', 'Is this character an engineer?', 'isEngineer');
INSERT INTO questions (id, text, attribute_key) VALUES ('q78', 'Is this character from a fantasy world?', 'isFromFantasyWorld');
INSERT INTO questions (id, text, attribute_key) VALUES ('q79', 'Is this character from Earth?', 'isFromEarth');
INSERT INTO questions (id, text, attribute_key) VALUES ('q80', 'Does this character have blonde hair?', 'hasBlondeHair');
INSERT INTO questions (id, text, attribute_key) VALUES ('q81', 'Does this character have blue eyes?', 'hasBlueEyes');
INSERT INTO questions (id, text, attribute_key) VALUES ('q82', 'Does this character have freckles?', 'hasFreckles');
INSERT INTO questions (id, text, attribute_key) VALUES ('q83', 'Does this character have a beard?', 'hasBeard');
INSERT INTO questions (id, text, attribute_key) VALUES ('q84', 'Is this character a vampire?', 'isVampire');
INSERT INTO questions (id, text, attribute_key) VALUES ('q85', 'Is this character a zombie?', 'isZombie');
INSERT INTO questions (id, text, attribute_key) VALUES ('q86', 'Is this character a ghost?', 'isGhost');
INSERT INTO questions (id, text, attribute_key) VALUES ('q87', 'Is this character a god or deity?', 'isGod');
INSERT INTO questions (id, text, attribute_key) VALUES ('q88', 'Is this character a demon?', 'isDemon');
INSERT INTO questions (id, text, attribute_key) VALUES ('q89', 'Is this character an elf?', 'isElf');
INSERT INTO questions (id, text, attribute_key) VALUES ('q90', 'Is this character a dwarf?', 'isDwarf');
INSERT INTO questions (id, text, attribute_key) VALUES ('q91', 'Is this character a giant?', 'isGiant');
INSERT INTO questions (id, text, attribute_key) VALUES ('q92', 'Is this character an orc?', 'isOrc');
INSERT INTO questions (id, text, attribute_key) VALUES ('q93', 'Is this character greedy?', 'isGreedy');
INSERT INTO questions (id, text, attribute_key) VALUES ('q94', 'Is this character brave?', 'isBrave');
INSERT INTO questions (id, text, attribute_key) VALUES ('q95', 'Is this character cowardly?', 'isCowardly');
INSERT INTO questions (id, text, attribute_key) VALUES ('q96', 'Is this character kind?', 'isKind');
INSERT INTO questions (id, text, attribute_key) VALUES ('q97', 'Is this character cruel?', 'isCruel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q98', 'Is this character intelligent?', 'isIntelligent');
INSERT INTO questions (id, text, attribute_key) VALUES ('q99', 'Is this character foolish?', 'isFoolish');
INSERT INTO questions (id, text, attribute_key) VALUES ('q100', 'Is this character rebellious?', 'isRebellious');
INSERT INTO questions (id, text, attribute_key) VALUES ('q101', 'Is this character loyal?', 'isLoyal');
INSERT INTO questions (id, text, attribute_key) VALUES ('q102', 'Is this character a traitor?', 'isTraitor');
INSERT INTO questions (id, text, attribute_key) VALUES ('q103', 'Is this character charming?', 'isCharming');
INSERT INTO questions (id, text, attribute_key) VALUES ('q104', 'Is this character clumsy?', 'isClumsy');
INSERT INTO questions (id, text, attribute_key) VALUES ('q105', 'Is this character sarcastic?', 'isSarcastic');
INSERT INTO questions (id, text, attribute_key) VALUES ('q106', 'Is this character naive?', 'isNaive');
INSERT INTO questions (id, text, attribute_key) VALUES ('q107', 'Is this character wise?', 'isWise');
INSERT INTO questions (id, text, attribute_key) VALUES ('q108', 'Is this character skeptical?', 'isSkeptical');
INSERT INTO questions (id, text, attribute_key) VALUES ('q109', 'Is this character optimistic?', 'isOptimistic');
INSERT INTO questions (id, text, attribute_key) VALUES ('q110', 'Is this character pessimistic?', 'isPessimistic');
INSERT INTO questions (id, text, attribute_key) VALUES ('q111', 'Is this character curious?', 'isCurious');
INSERT INTO questions (id, text, attribute_key) VALUES ('q112', 'Is this character cunning?', 'isCunning');
INSERT INTO questions (id, text, attribute_key) VALUES ('q113', 'Is this character honest?', 'isHonest');
INSERT INTO questions (id, text, attribute_key) VALUES ('q114', 'Is this character devious?', 'isDevious');
INSERT INTO questions (id, text, attribute_key) VALUES ('q115', 'Is this character humorous?', 'isHumorous');
INSERT INTO questions (id, text, attribute_key) VALUES ('q116', 'Is this character serious?', 'isSerious');
INSERT INTO questions (id, text, attribute_key) VALUES ('q117', 'Is this character adventurous?', 'isAdventurous');
INSERT INTO questions (id, text, attribute_key) VALUES ('q118', 'Is this character creative?', 'isCreative');
INSERT INTO questions (id, text, attribute_key) VALUES ('q119', 'Is this character lazy?', 'isLazy');
INSERT INTO questions (id, text, attribute_key) VALUES ('q120', 'Is this character energetic?', 'isEnergetic');
INSERT INTO questions (id, text, attribute_key) VALUES ('q121', 'Is this character patient?', 'isPatient');
INSERT INTO questions (id, text, attribute_key) VALUES ('q122', 'Is this character impatient?', 'isImpatient');
INSERT INTO questions (id, text, attribute_key) VALUES ('q123', 'Is this character rich?', 'isRich');
INSERT INTO questions (id, text, attribute_key) VALUES ('q124', 'Is this character poor?', 'isPoor');
INSERT INTO questions (id, text, attribute_key) VALUES ('q125', 'Does this character have super strength?', 'hasSuperStrength');
INSERT INTO questions (id, text, attribute_key) VALUES ('q126', 'Can this character turn invisible?', 'canTurnInvisible');
INSERT INTO questions (id, text, attribute_key) VALUES ('q127', 'Can this character control time?', 'canControlTime');
INSERT INTO questions (id, text, attribute_key) VALUES ('q128', 'Can this character create illusions?', 'canCreateIllusions');
INSERT INTO questions (id, text, attribute_key) VALUES ('q129', 'Can this character talk to animals?', 'canTalkToAnimals');
INSERT INTO questions (id, text, attribute_key) VALUES ('q130', 'Can this character generate electricity?', 'canGenerateElectricity');
INSERT INTO questions (id, text, attribute_key) VALUES ('q131', 'Can this character walk through walls?', 'canWalkThroughWalls');
INSERT INTO questions (id, text, attribute_key) VALUES ('q132', 'Does this character have long hair?', 'hasLongHair');
INSERT INTO questions (id, text, attribute_key) VALUES ('q133', 'Does this character have short hair?', 'hasShortHair');
INSERT INTO questions (id, text, attribute_key) VALUES ('q134', 'Is this character bald?', 'isBald');
INSERT INTO questions (id, text, attribute_key) VALUES ('q135', 'Does this character have a robot companion?', 'hasRobotCompanion');
INSERT INTO questions (id, text, attribute_key) VALUES ('q136', 'Does this character have an animal companion?', 'hasAnimalCompanion');
INSERT INTO questions (id, text, attribute_key) VALUES ('q137', 'Does this character have a sibling?', 'hasSibling');
INSERT INTO questions (id, text, attribute_key) VALUES ('q138', 'Is this character married?', 'isMarried');
INSERT INTO questions (id, text, attribute_key) VALUES ('q139', 'Is this character single?', 'isSingle');
INSERT INTO questions (id, text, attribute_key) VALUES ('q140', 'Does this character have children?', 'hasChildren');
INSERT INTO questions (id, text, attribute_key) VALUES ('q141', 'Is this character from the modern era?', 'isFromModernEra');
INSERT INTO questions (id, text, attribute_key) VALUES ('q142', 'Is this character from medieval times?', 'isFromMedievalTimes');
INSERT INTO questions (id, text, attribute_key) VALUES ('q143', 'Is this character from the future?', 'isFromFuture');
INSERT INTO questions (id, text, attribute_key) VALUES ('q144', 'Does this character appear in a sequel?', 'appearsInSequel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q145', 'Does this character appear in a prequel?', 'appearsInPrequel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q146', 'Is this character considered iconic?', 'isIconic');
INSERT INTO questions (id, text, attribute_key) VALUES ('q147', 'Does this character have a theme song?', 'hasThemeSong');
INSERT INTO questions (id, text, attribute_key) VALUES ('q148', 'Is this character part of a franchise?', 'isPartOfFranchise');
INSERT INTO questions (id, text, attribute_key) VALUES ('q149', 'Is this character from an indie source?', 'isFromIndieSource');
INSERT INTO questions (id, text, attribute_key) VALUES ('q150', 'Is this character based on a real person?', 'isBasedOnRealPerson');
INSERT INTO questions (id, text, attribute_key) VALUES ('q151', 'Is this character from historical fiction?', 'isFromHistoricalFiction');
INSERT INTO questions (id, text, attribute_key) VALUES ('q152', 'Does this character have a catchphrase?', 'hasCatchphrase');
INSERT INTO questions (id, text, attribute_key) VALUES ('q153', 'Is this character part of an ensemble cast?', 'isPartOfEnsembleCast');
INSERT INTO questions (id, text, attribute_key) VALUES ('q154', 'Is this character from an animated series?', 'isFromAnimatedSeries');
INSERT INTO questions (id, text, attribute_key) VALUES ('q155', 'Is this character from a live-action production?', 'isFromLiveAction');
INSERT INTO questions (id, text, attribute_key) VALUES ('q156', 'Is this character from the superhero genre?', 'isFromSuperheroGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q157', 'Is this character from the horror genre?', 'isFromHorrorGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q158', 'Is this character from the comedy genre?', 'isFromComedyGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q159', 'Is this character from the drama genre?', 'isFromDramaGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q160', 'Is this character from the romance genre?', 'isFromRomanceGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q161', 'Is this character from the science fiction genre?', 'isFromSciFiGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q162', 'Is this character from the fantasy genre?', 'isFromFantasyGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q163', 'Is this character from the mystery genre?', 'isFromMysteryGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q164', 'Is this character from the action genre?', 'isFromActionGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q165', 'Is this character from the thriller genre?', 'isFromThrillerGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q166', 'Is this character from the western genre?', 'isFromWesternGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q167', 'Is this character from the musical genre?', 'isFromMusicalGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q168', 'Is this character from a documentary?', 'isFromDocumentary');
INSERT INTO questions (id, text, attribute_key) VALUES ('q169', 'Is this character from the adventure genre?', 'isFromAdventureGenre');
INSERT INTO questions (id, text, attribute_key) VALUES ('q170', 'Is this character from a game show?', 'isFromGameShow');
INSERT INTO questions (id, text, attribute_key) VALUES ('q171', 'Is this character from a video game?', 'isVideoGameCharacter');
INSERT INTO questions (id, text, attribute_key) VALUES ('q172', 'Is this character from a comic book?', 'isFromComicBook');
INSERT INTO questions (id, text, attribute_key) VALUES ('q173', 'Is this character from an anime?', 'isFromAnime');
INSERT INTO questions (id, text, attribute_key) VALUES ('q174', 'Is this character from a cartoon?', 'isFromCartoon');
INSERT INTO questions (id, text, attribute_key) VALUES ('q175', 'Is this character from a TV show?', 'isFromTVShow');
INSERT INTO questions (id, text, attribute_key) VALUES ('q176', 'Is this character from a movie?', 'isFromMovie');
INSERT INTO questions (id, text, attribute_key) VALUES ('q177', 'Is this character from a book?', 'isFromBook');
INSERT INTO questions (id, text, attribute_key) VALUES ('q178', 'Is this character from pop culture?', 'isFromPopCulture');
INSERT INTO questions (id, text, attribute_key) VALUES ('q179', 'Is this character from a sitcom?', 'isFromSitcom');
INSERT INTO questions (id, text, attribute_key) VALUES ('q180', 'Is this character from a reality show?', 'isFromRealityShow');
INSERT INTO questions (id, text, attribute_key) VALUES ('q181', 'Is this character from a fantasy novel?', 'isFromFantasyNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q182', 'Is this character from a sci-fi novel?', 'isFromSciFiNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q183', 'Is this character from a mystery novel?', 'isFromMysteryNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q184', 'Is this character from a thriller novel?', 'isFromThrillerNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q185', 'Is this character from a romance novel?', 'isFromRomanceNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q186', 'Is this character from a horror novel?', 'isFromHorrorNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q187', 'Is this character from a historical novel?', 'isFromHistoricalNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q188', 'Is this character from an adventure novel?', 'isFromAdventureNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q189', 'Is this character from an action novel?', 'isFromActionNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q190', 'Is this character from a western novel?', 'isFromWesternNovel');
INSERT INTO questions (id, text, attribute_key) VALUES ('q191', 'Is this character female?', 'isFemale');
INSERT INTO questions (id, text, attribute_key) VALUES ('q192', 'Is this character non-binary?', 'isNonBinary');
INSERT INTO questions (id, text, attribute_key) VALUES ('q193', 'Is this character gender fluid?', 'isGenderFluid');
INSERT INTO questions (id, text, attribute_key) VALUES ('q194', 'Is this character transgender?', 'isTransgender');
INSERT INTO questions (id, text, attribute_key) VALUES ('q195', 'Is this character from a royal family?', 'isFromRoyalFamily');
INSERT INTO questions (id, text, attribute_key) VALUES ('q196', 'Is this character from the military?', 'isFromMilitary');
INSERT INTO questions (id, text, attribute_key) VALUES ('q197', 'Is this character from a noble family?', 'isFromNobleFamily');
INSERT INTO questions (id, text, attribute_key) VALUES ('q198', 'Is this character from a wealthy family?', 'isFromWealthyFamily');
INSERT INTO questions (id, text, attribute_key) VALUES ('q199', 'Is this character from a poor family?', 'isFromPoorFamily');
INSERT INTO questions (id, text, attribute_key) VALUES ('q200', 'Is this character from the middle class?', 'isFromMiddleClass');
INSERT INTO questions (id, text, attribute_key) VALUES ('q201', 'Is this character from the countryside?', 'isFromCountryside');
INSERT INTO questions (id, text, attribute_key) VALUES ('q202', 'Is this character from the city?', 'isFromCity');
INSERT INTO questions (id, text, attribute_key) VALUES ('q203', 'Is this character from a small town?', 'isFromSmallTown');
INSERT INTO questions (id, text, attribute_key) VALUES ('q204', 'Is this character from an island?', 'isFromIsland');
INSERT INTO questions (id, text, attribute_key) VALUES ('q205', 'Is this character from the jungle?', 'isFromJungle');
INSERT INTO questions (id, text, attribute_key) VALUES ('q206', 'Is this character from the desert?', 'isFromDesert');
INSERT INTO questions (id, text, attribute_key) VALUES ('q207', 'Is this character from the mountains?', 'isFromMountains');
INSERT INTO questions (id, text, attribute_key) VALUES ('q208', 'Is this character from an underground setting?', 'isFromUnderground');
INSERT INTO questions (id, text, attribute_key) VALUES ('q209', 'Is this character from the ocean?', 'isFromOcean');
INSERT INTO questions (id, text, attribute_key) VALUES ('q210', 'Is this character from the forest?', 'isFromForest');
INSERT INTO questions (id, text, attribute_key) VALUES ('q211', 'Is this character from the swamp?', 'isFromSwamp');
INSERT INTO questions (id, text, attribute_key) VALUES ('q212', 'Is this character from a castle?', 'isFromCastle');
INSERT INTO questions (id, text, attribute_key) VALUES ('q213', 'Is this character from a village?', 'isFromVillage');
INSERT INTO questions (id, text, attribute_key) VALUES ('q214', 'Is this character from a utopia?', 'isFromUtopia');
INSERT INTO questions (id, text, attribute_key) VALUES ('q215', 'Is this character from a dystopia?', 'isFromDystopia');
INSERT INTO questions (id, text, attribute_key) VALUES ('q216', 'Does this character have an accent?', 'hasAccent');
INSERT INTO questions (id, text, attribute_key) VALUES ('q217', 'Is this character mute?', 'isMute');
INSERT INTO questions (id, text, attribute_key) VALUES ('q218', 'Is this character deaf?', 'isDeaf');
INSERT INTO questions (id, text, attribute_key) VALUES ('q219', 'Is this character blind?', 'isBlind');
INSERT INTO questions (id, text, attribute_key) VALUES ('q220', 'Is this character disabled?', 'isDisabled');
INSERT INTO questions (id, text, attribute_key) VALUES ('q221', 'Is this character supernatural?', 'isSupernatural');
INSERT INTO questions (id, text, attribute_key) VALUES ('q222', 'Is this character mythical?', 'isMythical');
