-- Historical note: this file was created in error as a duplicate of 0011_optimize_indexes.sql.
-- Both files define the same idx_game_stats_user_created index with IF NOT EXISTS, so applying
-- this migration is idempotent. The index is canonically owned by 0011_optimize_indexes.sql.
-- This file is kept as a no-op to preserve the migration numbering visible in wrangler d1 migrations list.
