//
//  NativeServices-Swift.h
//  Andernator
//
//  Auto-generated Swift interface header.
//  This file is generated by Xcode to expose Swift classes to Objective-C.
//
//  Do not edit this file manually. It will be regenerated on each build.
//  To customize Swift visibility to Objective-C, use @objc attributes in Swift files.
//
//  Location: Build Settings → Objective-C Generated Interface Header Name
//  Default: Andernator-Swift.h
//

// This header is automatically generated by Xcode during build.
// It contains Objective-C interfaces for all @objc-marked Swift classes.
//
// React Native bridge will use this to discover and register:
//   - HapticsService
//   - VoiceOverAnnouncer
//   - ReduceMotionObserver
//   - LifecycleObserver
