// Auto-generated by scripts/generate-db-types.ts — do not edit manually
// Generated: 2026-04-19T22:11:58.251Z
// Source: migrations/*.sql

// ── D1 Row Types ──────────────────────────────────────────
// These types map 1:1 to D1 query result rows.
// D1 returns INTEGER as number, TEXT as string, NULL as null.

export interface CharactersRow {
  id: string
  name: string
  category: string
  source: string
  source_id: string | null
  popularity: number
  image_url: string | null
  description: string | null
  is_custom: number
  created_by: string | null
  created_at: number
}

export interface AttributeDefinitionsRow {
  key: string
  display_text: string
  question_text: string | null
  categories: string | null
  created_at: number
}

export interface CharacterAttributesRow {
  character_id: string
  attribute_key: string
  value: number | null
  confidence: number
}

export interface QuestionsRow {
  id: string
  text: string
  attribute_key: string
  priority: number
}

export interface GameStatsRow {
  id: number
  user_id: string
  won: number
  difficulty: string
  questions_asked: number
  character_pool_size: number
  created_at: number
  character_id: string | null
  character_name: string | null
  steps: string | null
}

export interface GameSessionsRow {
  id: string
  user_id: string
  character_ids: string
  answers: string
  current_question_attr: string | null
  difficulty: string
  max_questions: number
  created_at: number
  completed_at: number | null
}
