// Auto-generated by scripts/generate-db-types.ts — do not edit manually
// Generated: 2026-04-26T18:03:57.072Z
// Source: migrations/*.sql

// ── D1 Row Types ──────────────────────────────────────────
// These types map 1:1 to D1 query result rows.
// D1 returns INTEGER as number, TEXT as string, NULL as null.

export interface CharactersRow {
  id: string
  name: string
  category: string
  source: string
  source_id: string | null
  popularity: number
  image_url: string | null
  description: string | null
  is_custom: number
  created_by: string | null
  created_at: number
  attribute_count: number
  attributes_json: string
}

export interface AttributeDefinitionsRow {
  key: string
  display_text: string
  question_text: string | null
  categories: string | null
  created_at: number
  is_active: number
}

export interface CharacterAttributesRow {
  character_id: string
  attribute_key: string
  value: number | null
  confidence: number
}

export interface QuestionsRow {
  id: string
  text: string
  attribute_key: string
  priority: number
}

export interface GameStatsRow {
  id: number
  user_id: string
  won: number
  difficulty: string
  questions_asked: number
  character_pool_size: number
  created_at: number
  character_id: string | null
  character_name: string | null
  steps: string | null
  guesses_used: number
  confidence_at_guess: number | null
  entropy_at_guess: number | null
  remaining_at_guess: number | null
  answer_distribution: string | null
  guess_trigger: string | null
  forced_guess: number
  gap_at_guess: number | null
  alive_count_at_guess: number | null
  questions_remaining_at_guess: number | null
}

export interface GameSessionsRow {
  id: string
  user_id: string
  character_ids: string
  answers: string
  current_question_attr: string | null
  difficulty: string
  max_questions: number
  created_at: number
  completed_at: number | null
  dropped_at_phase: string | null
}

export interface GameRevealsRow {
  id: number
  actual_character_name: string
  actual_character_id: string | null
  answers: string
  attributes_filled: number
  discrepancies: number
  created_at: number
}

export interface SimGameStatsRow {
  id: number
  run_id: string
  target_character_id: string
  target_character_name: string
  won: number
  questions_asked: number
  guesses_used: number
  guess_trigger: string | null
  forced_guess: number
  confidence_at_guess: number | null
  entropy_at_guess: number | null
  gap_at_guess: number | null
  alive_count_at_guess: number | null
  second_best_character_id: string | null
  second_best_character_name: string | null
  second_best_probability: number | null
  questions_sequence: string | null
  answer_distribution: string | null
  character_pool_size: number | null
  max_questions: number | null
  difficulty: string
  created_at: number
}

export interface PipelineRunsRow {
  id: number
  run_batch: string
  character_id: string
  step: string
  status: string
  error: string | null
  duration_ms: number | null
  created_at: number
}

export interface ProposedAttributesRow {
  id: number
  key: string
  display_text: string
  question_text: string
  rationale: string | null
  example_chars: string | null
  proposed_by: string
  status: string
  reviewed_by: string | null
  reviewed_at: number | null
  created_at: number
}

export interface ClientEventsRow {
  id: string
  session_id: string | null
  user_id: string | null
  event_type: string
  data: string | null
  client_ts: number | null
  created_at: number
}

export interface AttributeDisputesRow {
  id: number
  character_id: string
  attribute_key: string
  current_value: number | null
  dispute_reason: string
  confidence: number
  disputed_by: string
  created_at: number
  status: string
  resolved_by: string | null
  resolved_at: number | null
}

export interface ErrorLogsRow {
  id: number
  level: string
  source: string
  message: string
  detail: string | null
  created_at: number
}
