/**
 * Simulation CLI runner.
 *
 * Usage:
 *   pnpm simulate                              # 50 random characters, medium difficulty
 *   pnpm simulate --all                        # every character in the pool
 *   pnpm simulate --target <id>                # single character
 *   pnpm simulate --sample 200 --difficulty hard
 *   pnpm simulate --output results.jsonl       # write JSONL file
 *   pnpm simulate --write-db                   # write results to D1 sim_game_stats table
 *   pnpm simulate --write-db --env preview     # write to preview DB
 *
 * Requires:
 *   scripts/simulate/data/characters.json   (generated by pnpm simulate:export)
 *   scripts/simulate/data/questions.json
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { simulateGame, DIFFICULTY_MAP } from './engine.js'
import type { SimCharacter, SimQuestion, SimGameResult } from './engine.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DATA_DIR = join(__dirname, 'data')

// ── CLI args ──────────────────────────────────────────────────────────────────

function flag(name: string): boolean {
  return process.argv.includes(`--${name}`)
}

function arg(name: string): string | null {
  const idx = process.argv.indexOf(`--${name}`)
  return idx !== -1 ? (process.argv[idx + 1] ?? null) : null
}

const ALL = flag('all')
const TARGET_ID = arg('target')
const SAMPLE = ALL ? null : parseInt(arg('sample') ?? '50', 10)
const DIFFICULTY = arg('difficulty') ?? 'medium'
const OUTPUT_FILE = arg('output')
const WRITE_DB = flag('write-db')
const ENV = arg('env') ?? 'production'
const POOL_SIZE_OVERRIDE = arg('pool-size') ? parseInt(arg('pool-size')!, 10) : undefined

if (!DIFFICULTY_MAP[DIFFICULTY]) {
  console.error(`Unknown difficulty: "${DIFFICULTY}". Choose easy, medium, or hard.`)
  process.exit(1)
}

// ── Load data ─────────────────────────────────────────────────────────────────

const characterPath = join(DATA_DIR, 'characters.json')
const questionPath = join(DATA_DIR, 'questions.json')

if (!existsSync(characterPath) || !existsSync(questionPath)) {
  console.error('Data files not found. Run `pnpm simulate:export` first.')
  process.exit(1)
}

const allCharacters: SimCharacter[] = JSON.parse(readFileSync(characterPath, 'utf8'))
const questions: SimQuestion[] = JSON.parse(readFileSync(questionPath, 'utf8'))

if (allCharacters.length === 0 || questions.length === 0) {
  console.error('Empty character or question data. Re-run `pnpm simulate:export`.')
  process.exit(1)
}

// ── Select targets ────────────────────────────────────────────────────────────

let targets: SimCharacter[]

if (TARGET_ID) {
  const found = allCharacters.find((c) => c.id === TARGET_ID)
  if (!found) {
    console.error(`Character not found: "${TARGET_ID}"`)
    process.exit(1)
  }
  targets = [found]
} else if (ALL) {
  targets = allCharacters
} else {
  // Random sample without replacement
  const shuffled = allCharacters.slice().sort(() => Math.random() - 0.5)
  targets = shuffled.slice(0, SAMPLE!)
}

// ── Run simulations ───────────────────────────────────────────────────────────

const runId = crypto.randomUUID()
const results: SimGameResult[] = []
const startTime = Date.now()

console.log(`\nSimulation run: ${runId}`)
console.log(`Targets: ${targets.length} | Pool: ${allCharacters.length} characters | Difficulty: ${DIFFICULTY}`)
console.log(`Questions: ${questions.length}\n`)

for (let i = 0; i < targets.length; i++) {
  const target = targets[i]!
  const result = simulateGame(target, allCharacters, questions, runId, {
    difficulty: DIFFICULTY,
    poolSize: POOL_SIZE_OVERRIDE,
  })
  results.push(result)

  const indicator = result.won ? '✓' : '✗'
  const pct = Math.round(confidenceOrZero(result.confidenceAtGuess) * 100)
  process.stdout.write(
    `  [${String(i + 1).padStart(4)}/${targets.length}] ${indicator} ${target.name.padEnd(28)} ` +
    `${String(result.questionsAsked).padStart(2)}q  ${pct.toString().padStart(3)}% conf  ${result.guessTrigger ?? 'n/a'}\n`
  )
}

const elapsed = ((Date.now() - startTime) / 1000).toFixed(1)
const wins = results.filter((r) => r.won).length
const winRate = ((wins / results.length) * 100).toFixed(1)
const avgQ = (results.reduce((s, r) => s + r.questionsAsked, 0) / results.length).toFixed(1)
const avgConf = (results.reduce((s, r) => s + confidenceOrZero(r.confidenceAtGuess), 0) / results.length * 100).toFixed(1)

console.log('\n── Summary ──────────────────────────────────────────────')
console.log(`  Total:     ${results.length} games in ${elapsed}s`)
console.log(`  Win rate:  ${wins}/${results.length} (${winRate}%)`)
console.log(`  Avg questions: ${avgQ}`)
console.log(`  Avg confidence at guess: ${avgConf}%`)

const triggerCounts: Record<string, number> = {}
for (const r of results) {
  const t = r.guessTrigger ?? 'none'
  triggerCounts[t] = (triggerCounts[t] ?? 0) + 1
}
console.log('  Triggers:', Object.entries(triggerCounts).map(([k, v]) => `${k}=${v}`).join('  '))
console.log('─────────────────────────────────────────────────────────\n')

function confidenceOrZero(v: number | null): number { return v ?? 0 }

// ── JSONL output ──────────────────────────────────────────────────────────────

if (OUTPUT_FILE) {
  const outPath = OUTPUT_FILE.startsWith('/') ? OUTPUT_FILE : join(process.cwd(), OUTPUT_FILE)
  const lines = results.map((r) => JSON.stringify(r)).join('\n') + '\n'
  writeFileSync(outPath, lines, 'utf8')
  console.log(`Results written to ${outPath}`)
}

// ── D1 write-back ─────────────────────────────────────────────────────────────

if (WRITE_DB) {
  const DB_NAME = ENV === 'production' ? 'guess-db' : 'guess-db-preview'
  const ENV_FLAG = ENV === 'production' ? '--env production' : '--env preview'

  console.log(`Writing ${results.length} rows to ${DB_NAME} sim_game_stats...`)

  // Batch into chunks of 500 to stay within D1 file size limits
  const BATCH_SIZE = 500
  const tmpDir = join(__dirname, 'data', '.tmp')
  mkdirSync(tmpDir, { recursive: true })

  for (let batchStart = 0; batchStart < results.length; batchStart += BATCH_SIZE) {
    const batch = results.slice(batchStart, batchStart + BATCH_SIZE)
    const batchNum = Math.floor(batchStart / BATCH_SIZE) + 1

    const inserts = batch.map((r) => {
      const qs = JSON.stringify(r.questionsSequence).replace(/'/g, "''")
      const ad = JSON.stringify(r.answerDistribution).replace(/'/g, "''")
      return `INSERT INTO sim_game_stats (run_id, target_character_id, target_character_name, won, questions_asked, guesses_used, guess_trigger, forced_guess, confidence_at_guess, entropy_at_guess, gap_at_guess, alive_count_at_guess, second_best_character_id, second_best_character_name, second_best_probability, questions_sequence, answer_distribution, character_pool_size, max_questions, difficulty, created_at) VALUES ('${r.runId}', '${r.targetCharacterId}', '${r.targetCharacterName.replace(/'/g, "''")}', ${r.won ? 1 : 0}, ${r.questionsAsked}, ${r.guessesUsed}, ${r.guessTrigger ? `'${r.guessTrigger}'` : 'NULL'}, ${r.forcedGuess ? 1 : 0}, ${r.confidenceAtGuess ?? 'NULL'}, ${r.entropyAtGuess ?? 'NULL'}, ${r.gapAtGuess ?? 'NULL'}, ${r.aliveCountAtGuess ?? 'NULL'}, ${r.secondBestCharacterId ? `'${r.secondBestCharacterId}'` : 'NULL'}, ${r.secondBestCharacterName ? `'${r.secondBestCharacterName.replace(/'/g, "''")}'` : 'NULL'}, ${r.secondBestProbability ?? 'NULL'}, '${qs}', '${ad}', ${r.characterPoolSize}, ${r.maxQuestions}, '${r.difficulty}', ${r.createdAt});`
    }).join('\n')

    const tmpFile = join(tmpDir, `batch_${batchNum}.sql`)
    writeFileSync(tmpFile, inserts, 'utf8')

    try {
      execSync(
        `npx wrangler d1 execute ${DB_NAME} ${ENV_FLAG} --remote --file="${tmpFile}"`,
        { stdio: 'inherit' }
      )
      console.log(`  Batch ${batchNum}: ${batch.length} rows written`)
    } catch (err) {
      console.error(`  Batch ${batchNum} failed:`, err)
    }
  }

  console.log('\nDB write complete.')
}
