/**
 * Simulation CLI runner.
 *
 * Usage:
 *   pnpm simulate                              # 50 random characters, medium difficulty
 *   pnpm simulate --all                        # every character in the pool
 *   pnpm simulate --target <id>                # single character
 *   pnpm simulate --sample 200 --difficulty hard
 *   pnpm simulate --output results.jsonl       # write JSONL file
 *   pnpm simulate --write-db                   # write results to D1 sim_game_stats table
 *   pnpm simulate --write-db --env preview     # write to preview DB
 *
 * Requires:
 *   scripts/simulate/data/characters.json   (generated by pnpm simulate:export)
 *   scripts/simulate/data/questions.json
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { execSync, spawnSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads'
import { cpus } from 'node:os'
import { simulateGame, DIFFICULTY_MAP } from './engine.js'
import type { SimCharacter, SimQuestion, SimGameResult, SimulateOptions } from './engine.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DATA_DIR = join(__dirname, 'data')

// ── Worker thread short-circuit (S.6) ────────────────────────────────────────
// When spawned as a worker, receive a character slice, run simulations, return results.

interface WorkerPayload {
  targets: SimCharacter[]
  pool: SimCharacter[]
  questions: SimQuestion[]
  runId: string
  options: SimulateOptions
}

if (!isMainThread) {
  const payload = workerData as WorkerPayload
  const results: SimGameResult[] = payload.targets.map((target) =>
    simulateGame(target, payload.pool, payload.questions, payload.runId, payload.options)
  )
  parentPort!.postMessage({ results })
  process.exit(0)
}

// ── CLI args ──────────────────────────────────────────────────────────────────

function flag(name: string): boolean {
  return process.argv.includes(`--${name}`)
}

function arg(name: string): string | null {
  const idx = process.argv.indexOf(`--${name}`)
  return idx !== -1 ? (process.argv[idx + 1] ?? null) : null
}

const ALL = flag('all')
const TARGET_ID = arg('target')
const SAMPLE = ALL ? null : parseInt(arg('sample') ?? '50', 10)
const DIFFICULTY = arg('difficulty') ?? 'medium'
const OUTPUT_FILE = arg('output')
const WRITE_DB = flag('write-db')
const ENV = arg('env') ?? 'production'
const POOL_SIZE_OVERRIDE = arg('pool-size') ? parseInt(arg('pool-size')!, 10) : undefined
const MIN_ATTRS_OVERRIDE = arg('min-attrs') ? parseInt(arg('min-attrs')!, 10) : null
const NOISE = arg('noise') ? parseFloat(arg('noise')!) / 100 : 0 // --noise 10 → 0.10
/** Shuffle questions N times per target and report win-rate variance (fragility). */
const SENSITIVITY = arg('sensitivity') ? parseInt(arg('sensitivity')!, 10) : 0
/** Use Node worker_threads for parallel execution (splits pool across CPU cores). */
const PARALLEL = flag('parallel')

if (NOISE < 0 || NOISE > 1) {
  console.error(`--noise must be 0–100 (got ${arg('noise')})`)
  process.exit(1)
}

// ── --compare short-circuit ───────────────────────────────────────────────────

const COMPARE_ARGS = (() => {
  const idx = process.argv.indexOf('--compare')
  if (idx === -1) return null
  const a = process.argv[idx + 1]
  const b = process.argv[idx + 2]
  return a && b ? [a, b] : null
})()

if (COMPARE_ARGS) {
  const compareScript = join(__dirname, 'compare.ts')
  const result = spawnSync('npx', ['tsx', compareScript, ...COMPARE_ARGS], { stdio: 'inherit' })
  process.exit(result.status ?? 0)
}

if (!DIFFICULTY_MAP[DIFFICULTY]) {
  console.error(`Unknown difficulty: "${DIFFICULTY}". Choose easy, medium, or hard.`)
  process.exit(1)
}

// ── Load data ─────────────────────────────────────────────────────────────────

const characterPath = join(DATA_DIR, 'characters.json')
const questionPath = join(DATA_DIR, 'questions.json')

if (!existsSync(characterPath) || !existsSync(questionPath)) {
  console.error('Data files not found. Run `pnpm simulate:export` first.')
  process.exit(1)
}

const allCharacters: SimCharacter[] = JSON.parse(readFileSync(characterPath, 'utf8'))
const questions: SimQuestion[] = JSON.parse(readFileSync(questionPath, 'utf8'))

if (allCharacters.length === 0 || questions.length === 0) {
  console.error('Empty character or question data. Re-run `pnpm simulate:export`.')
  process.exit(1)
}

// Apply minimum attribute count filter if requested (mirrors MIN_ATTRIBUTES in _game-engine.ts)
const eligibleCharacters = MIN_ATTRS_OVERRIDE != null
  ? allCharacters.filter((c) => {
      const knownCount = Object.values(c.attributes).filter((v) => v !== null).length
      return knownCount >= MIN_ATTRS_OVERRIDE
    })
  : allCharacters

if (MIN_ATTRS_OVERRIDE != null) {
  console.log(`Min-attrs filter: ${MIN_ATTRS_OVERRIDE} — pool ${allCharacters.length} → ${eligibleCharacters.length} chars`)
}

// ── Select targets ────────────────────────────────────────────────────────────

let targets: SimCharacter[]

if (TARGET_ID) {
  const found = eligibleCharacters.find((c) => c.id === TARGET_ID)
  if (!found) {
    console.error(`Character not found: "${TARGET_ID}"`)
    process.exit(1)
  }
  targets = [found]
} else if (ALL) {
  targets = eligibleCharacters
} else {
  // Random sample without replacement
  const shuffled = eligibleCharacters.slice().sort(() => Math.random() - 0.5)
  targets = shuffled.slice(0, SAMPLE!)
}

// ── Run simulations ───────────────────────────────────────────────────────────

const runId = crypto.randomUUID()
const results: SimGameResult[] = []
const startTime = Date.now()

const simOptions: SimulateOptions = {
  difficulty: DIFFICULTY,
  poolSize: POOL_SIZE_OVERRIDE,
  noise: NOISE,
}

console.log(`\nSimulation run: ${runId}`)
console.log(`Targets: ${targets.length} | Pool: ${eligibleCharacters.length} characters | Difficulty: ${DIFFICULTY}${NOISE > 0 ? ` | Noise: ${(NOISE * 100).toFixed(0)}%` : ''}${PARALLEL ? ` | Parallel: ${Math.max(1, cpus().length - 1)} workers` : ''}`)
console.log(`Questions: ${questions.length}\n`)

if (PARALLEL && targets.length > 1) {
  // ── Parallel mode: split across worker threads ──────────────────────────────
  const workerCount = Math.max(1, Math.min(cpus().length - 1, targets.length))
  const chunkSize = Math.ceil(targets.length / workerCount)
  const chunks: SimCharacter[][] = []
  for (let i = 0; i < targets.length; i += chunkSize) {
    chunks.push(targets.slice(i, i + chunkSize))
  }

  // Use a .mjs shim that registers tsx hooks before importing run.ts.
  // Worker threads do not inherit the parent's ESM hooks (tsx), so we must
  // re-register them explicitly inside each worker.
  const workerUrl = new URL('./worker-shim.mjs', import.meta.url)
  const workerResults = await Promise.all(
    chunks.map(
      (chunk) =>
        new Promise<SimGameResult[]>((resolve, reject) => {
          const payload: WorkerPayload = {
            targets: chunk,
            pool: eligibleCharacters,
            questions,
            runId,
            options: simOptions,
          }
          const worker = new Worker(workerUrl, {
            workerData: payload,
          })
          worker.on('message', (msg: { results: SimGameResult[] }) => resolve(msg.results))
          worker.on('error', reject)
          worker.on('exit', (code) => {
            if (code !== 0) reject(new Error(`Worker exited with code ${code}`))
          })
        })
    )
  )

  for (const chunk of workerResults) {
    results.push(...chunk)
  }

  // Print per-result summary (no live progress in parallel mode)
  for (const result of results) {
    const indicator = result.won ? '✓' : '✗'
    const pct = Math.round(confidenceOrZero(result.confidenceAtGuess) * 100)
    process.stdout.write(
      `  ${indicator} ${result.targetCharacterName.padEnd(28)} ` +
      `${String(result.questionsAsked).padStart(2)}q  ${pct.toString().padStart(3)}% conf  ${result.guessTrigger ?? 'n/a'}\n`
    )
  }
} else {
  // ── Single-threaded mode ────────────────────────────────────────────────────
  for (let i = 0; i < targets.length; i++) {
    const target = targets[i]!
    const result = simulateGame(target, eligibleCharacters, questions, runId, simOptions)
    results.push(result)

    const indicator = result.won ? '✓' : '✗'
    const pct = Math.round(confidenceOrZero(result.confidenceAtGuess) * 100)
    process.stdout.write(
      `  [${String(i + 1).padStart(4)}/${targets.length}] ${indicator} ${target.name.padEnd(28)} ` +
      `${String(result.questionsAsked).padStart(2)}q  ${pct.toString().padStart(3)}% conf  ${result.guessTrigger ?? 'n/a'}\n`
    )
  }
}

function confidenceOrZero(v: number | null): number { return v ?? 0 }

const elapsed = ((Date.now() - startTime) / 1000).toFixed(1)
const wins = results.filter((r) => r.won).length
const winRate = ((wins / results.length) * 100).toFixed(1)
const avgQ = (results.reduce((s, r) => s + r.questionsAsked, 0) / results.length).toFixed(1)
const avgConf = (results.reduce((s, r) => s + confidenceOrZero(r.confidenceAtGuess), 0) / results.length * 100).toFixed(1)

console.log('\n── Summary ──────────────────────────────────────────────')
console.log(`  Total:     ${results.length} games in ${elapsed}s`)
console.log(`  Win rate:  ${wins}/${results.length} (${winRate}%)`)
console.log(`  Avg questions: ${avgQ}`)
console.log(`  Avg confidence at guess: ${avgConf}%`)

const triggerCounts: Record<string, number> = {}
for (const r of results) {
  const t = r.guessTrigger ?? 'none'
  triggerCounts[t] = (triggerCounts[t] ?? 0) + 1
}
console.log('  Triggers:', Object.entries(triggerCounts).map(([k, v]) => `${k}=${v}`).join('  '))
console.log('─────────────────────────────────────────────────────────\n')

// ── Sensitivity analysis (S.7) ────────────────────────────────────────────────
// --sensitivity <N>: for each target, re-run N times with shuffled question list
// to measure how fragile the win is to question ordering.

function stddev(values: number[]): number {
  if (values.length < 2) return 0
  const mean = values.reduce((a, b) => a + b, 0) / values.length
  return Math.sqrt(values.reduce((s, v) => s + (v - mean) ** 2, 0) / values.length)
}

function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice()
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j]!, a[i]!]
  }
  return a
}

if (SENSITIVITY > 0) {
  console.log(`\nSensitivity analysis: ${SENSITIVITY} shuffles per character…\n`)

  interface SensitivityRow {
    id: string
    name: string
    baseWon: boolean
    shuffleWins: number
    shuffleWinRate: number
    shuffleAvgQ: number
    fragility: number
  }

  const sensRows: SensitivityRow[] = []
  const sensitivityRunId = crypto.randomUUID()

  for (const target of targets) {
    const baseResult = results.find((r) => r.targetCharacterId === target.id)
    const shuffleWonArr: number[] = []
    const shuffleQArr: number[] = []

    for (let n = 0; n < SENSITIVITY; n++) {
      const shuffledQuestions = shuffle(questions)
      const r = simulateGame(target, eligibleCharacters, shuffledQuestions, sensitivityRunId, simOptions)
      shuffleWonArr.push(r.won ? 1 : 0)
      shuffleQArr.push(r.questionsAsked)
    }

    const shuffleWins = shuffleWonArr.reduce((a, b) => a + b, 0)
    const shuffleWinRate = shuffleWins / SENSITIVITY
    const shuffleAvgQ = shuffleQArr.reduce((a, b) => a + b, 0) / SENSITIVITY
    const fragility = stddev(shuffleWonArr)

    sensRows.push({
      id: target.id,
      name: target.name,
      baseWon: baseResult?.won ?? false,
      shuffleWins,
      shuffleWinRate,
      shuffleAvgQ,
      fragility,
    })
  }

  sensRows.sort((a, b) => b.fragility - a.fragility)

  console.log('── Sensitivity Report (sorted by fragility) ─────────────────────────────────')
  console.log(
    `  ${'Character'.padEnd(32)} ${'Base'.padStart(4)} ${'ShuffleWin%'.padStart(11)} ${'AvgQ'.padStart(5)} ${'Fragility'.padStart(9)}`
  )
  console.log('  ' + '─'.repeat(66))
  for (const row of sensRows) {
    console.log(
      `  ${row.name.padEnd(32)} ${(row.baseWon ? '✓' : '✗').padStart(4)} ` +
      `${(row.shuffleWinRate * 100).toFixed(1).padStart(10)}% ` +
      `${row.shuffleAvgQ.toFixed(1).padStart(5)} ` +
      `${row.fragility.toFixed(4).padStart(9)}`
    )
  }
  console.log('─'.repeat(70) + '\n')

  if (OUTPUT_FILE) {
    const base = OUTPUT_FILE.replace(/\.jsonl$/, '')
    const sensPath = (base + '-sensitivity.jsonl').startsWith('/')
      ? base + '-sensitivity.jsonl'
      : join(process.cwd(), base + '-sensitivity.jsonl')
    writeFileSync(sensPath, sensRows.map((r) => JSON.stringify(r)).join('\n') + '\n', 'utf8')
    console.log(`Sensitivity report written to ${sensPath}`)
  }
}

// ── JSONL output ──────────────────────────────────────────────────────────────

if (OUTPUT_FILE) {
  const outPath = OUTPUT_FILE.startsWith('/') ? OUTPUT_FILE : join(process.cwd(), OUTPUT_FILE)
  const lines = results.map((r) => JSON.stringify(r)).join('\n') + '\n'
  writeFileSync(outPath, lines, 'utf8')
  console.log(`Results written to ${outPath}`)
}

// ── D1 write-back ─────────────────────────────────────────────────────────────

if (WRITE_DB) {
  const DB_NAME = ENV === 'production' ? 'guess-db' : 'guess-db-preview'
  const ENV_FLAG = ENV === 'production' ? '--env production' : '--env preview'

  console.log(`Writing ${results.length} rows to ${DB_NAME} sim_game_stats...`)

  // Batch into chunks of 500 to stay within D1 file size limits
  const BATCH_SIZE = 500
  const tmpDir = join(__dirname, 'data', '.tmp')
  mkdirSync(tmpDir, { recursive: true })

  for (let batchStart = 0; batchStart < results.length; batchStart += BATCH_SIZE) {
    const batch = results.slice(batchStart, batchStart + BATCH_SIZE)
    const batchNum = Math.floor(batchStart / BATCH_SIZE) + 1

    const inserts = batch.map((r) => {
      const qs = JSON.stringify(r.questionsSequence).replace(/'/g, "''")
      const ad = JSON.stringify(r.answerDistribution).replace(/'/g, "''")
      return `INSERT INTO sim_game_stats (run_id, target_character_id, target_character_name, won, questions_asked, guesses_used, guess_trigger, forced_guess, confidence_at_guess, entropy_at_guess, gap_at_guess, alive_count_at_guess, second_best_character_id, second_best_character_name, second_best_probability, questions_sequence, answer_distribution, character_pool_size, max_questions, difficulty, noise, created_at) VALUES ('${r.runId}', '${r.targetCharacterId}', '${r.targetCharacterName.replace(/'/g, "''")}', ${r.won ? 1 : 0}, ${r.questionsAsked}, ${r.guessesUsed}, ${r.guessTrigger ? `'${r.guessTrigger}'` : 'NULL'}, ${r.forcedGuess ? 1 : 0}, ${r.confidenceAtGuess ?? 'NULL'}, ${r.entropyAtGuess ?? 'NULL'}, ${r.gapAtGuess ?? 'NULL'}, ${r.aliveCountAtGuess ?? 'NULL'}, ${r.secondBestCharacterId ? `'${r.secondBestCharacterId}'` : 'NULL'}, ${r.secondBestCharacterName ? `'${r.secondBestCharacterName.replace(/'/g, "''")}'` : 'NULL'}, ${r.secondBestProbability ?? 'NULL'}, '${qs}', '${ad}', ${r.characterPoolSize}, ${r.maxQuestions}, '${r.difficulty}', ${r.noise}, ${r.createdAt});`
    }).join('\n')

    const tmpFile = join(tmpDir, `batch_${batchNum}.sql`)
    writeFileSync(tmpFile, inserts, 'utf8')

    try {
      execSync(
        `npx wrangler d1 execute ${DB_NAME} ${ENV_FLAG} --remote --file="${tmpFile}"`,
        { stdio: 'inherit' }
      )
      console.log(`  Batch ${batchNum}: ${batch.length} rows written`)
    } catch (err) {
      console.error(`  Batch ${batchNum} failed:`, err)
    }
  }

  console.log('\nDB write complete.')
}
