#!/usr/bin/env tsx
/**
 * pnpm api:generate — produce a typed API client surface from docs/openapi.yaml
 *
 * Wraps openapi-typescript to emit `src/lib/api.generated.ts`, which is the
 * `paths`/`components`/`operations` shape consumed by `openapi-fetch`'s
 * `createClient<paths>()`. This is the codegen half of DX.v2.1; the runtime
 * client wrapper lives at `src/lib/apiClient.ts` and the consumer migrations
 * (useServerGame, adminApi) are tracked under RF.v2.1 + RF.v2.5.
 *
 * Modes:
 *   pnpm api:generate           — write src/lib/api.generated.ts
 *   pnpm api:generate --check   — fail with diff if the file is out of sync
 *
 * The check mode is wired into CI via the existing openapi check workflow.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'

const ROOT = process.cwd()
const SPEC = resolve(ROOT, 'docs/openapi.yaml')
const OUT = resolve(ROOT, 'src/lib/api.generated.ts')
const HEADER = `/**
 * GENERATED by scripts/api/generate-client.ts — do not edit by hand.
 * Source of truth: docs/openapi.yaml.
 * Run \`pnpm api:generate\` after editing handler decorators + \`pnpm openapi:generate\`.
 *
 * Consumed by openapi-fetch via createClient<paths>() in src/lib/apiClient.ts.
 */
`

async function buildClient(): Promise<string> {
  const ast = await openapiTS(new URL(`file://${SPEC}`))
  return HEADER + '\n' + astToString(ast)
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check')
  const next = await buildClient()

  if (check) {
    let current = ''
    try {
      current = readFileSync(OUT, 'utf8')
    } catch {
      console.error(`✗ ${OUT} does not exist. Run \`pnpm api:generate\` and commit the file.`)
      process.exit(1)
    }
    if (current === next) {
      console.log(`✓ ${OUT} in sync with docs/openapi.yaml`)
      return
    }
    console.error(`✗ ${OUT} is out of sync with docs/openapi.yaml.`)
    console.error('  Run `pnpm api:generate` and commit the result.')
    process.exit(1)
  }

  writeFileSync(OUT, next, 'utf8')
  console.log(`✓ wrote ${OUT} (${next.length.toLocaleString()} chars)`)
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : String(err))
  process.exit(1)
})
