#!/usr/bin/env tsx
/**
 * generate-db-types.ts
 *
 * Parses SQL migration files and generates TypeScript row types
 * for each D1 table. Output: functions/api/_db-types.ts
 *
 * Usage: pnpm db:types
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const MIGRATIONS_DIR = resolve(import.meta.dirname ?? '.', '..', 'migrations')
const OUTPUT_FILE = resolve(
  import.meta.dirname ?? '.',
  '..',
  'functions',
  'api',
  '_db-types.ts'
)

// ── SQL type → TS type mapping ──────────────────────────────

interface Column {
  name: string
  tsType: string
  nullable: boolean
}

interface Table {
  name: string
  columns: Column[]
}

function sqlTypeToTs(sqlType: string): string {
  const upper = sqlType.toUpperCase()
  if (upper.startsWith('INTEGER') || upper.startsWith('REAL') || upper.startsWith('NUMERIC')) {
    return 'number'
  }
  if (upper.startsWith('TEXT') || upper.startsWith('VARCHAR') || upper.startsWith('CHAR')) {
    return 'string'
  }
  if (upper.startsWith('BLOB')) return 'ArrayBuffer'
  return 'unknown'
}

function toPascalCase(s: string): string {
  return s
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

// ── Strip SQL comments ──────────────────────────────────────

function stripComments(sql: string): string {
  return sql
    .replace(/--[^\n]*/g, '') // line comments
    .replace(/\/\*[\s\S]*?\*\//g, '') // block comments
}

// ── Parse CREATE TABLE statements ───────────────────────────

function parseCreateTable(sql: string): Table[] {
  const tables: Table[] = []
  const cleanSql = stripComments(sql)

  // Match CREATE TABLE blocks
  const createRegex =
    /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\(([\s\S]*?)\);/gi
  let match: RegExpExecArray | null

  while ((match = createRegex.exec(cleanSql)) !== null) {
    const tableName = match[1]
    const body = match[2]
    const columns: Column[] = []

    // Split on commas, but respect parentheses (for CHECK constraints, etc.)
    const lines = splitColumnDefs(body)

    for (const line of lines) {
      const trimmed = line.trim()
      // Skip constraints: PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, etc.
      if (/^(PRIMARY\s+KEY|FOREIGN\s+KEY|UNIQUE|CHECK|CONSTRAINT)\b/i.test(trimmed)) {
        continue
      }

      // Parse: column_name TYPE [constraints...]
      const colMatch = trimmed.match(/^(\w+)\s+(\w+(?:\([^)]*\))?)\s*(.*)/i)
      if (!colMatch) continue

      const colName = colMatch[1]
      const colType = colMatch[2]
      const constraints = colMatch[3].toUpperCase()

      const isNotNull = constraints.includes('NOT NULL')
      const isPrimaryKey = constraints.includes('PRIMARY KEY')
      const hasDefault = constraints.includes('DEFAULT')
      // A column is nullable if it's not NOT NULL and not PRIMARY KEY
      // But DEFAULT NULL or no NOT NULL means it can be null in query results
      const nullable = !isNotNull && !isPrimaryKey

      columns.push({
        name: colName,
        tsType: sqlTypeToTs(colType),
        nullable: nullable && !hasDefault,
      })
    }

    tables.push({ name: tableName, columns })
  }

  return tables
}

// ── Parse ALTER TABLE ADD COLUMN ────────────────────────────

function parseAlterAddColumn(
  sql: string,
  tables: Map<string, Table>
): void {
  const cleanSql = stripComments(sql)
  const alterRegex =
    /ALTER\s+TABLE\s+(\w+)\s+ADD\s+COLUMN\s+(\w+)\s+(\w+(?:\([^)]*\))?)\s*(.*?);/gi
  let match: RegExpExecArray | null

  while ((match = alterRegex.exec(cleanSql)) !== null) {
    const tableName = match[1]
    const colName = match[2]
    const colType = match[3]
    const constraints = (match[4] || '').toUpperCase()

    const table = tables.get(tableName)
    if (!table) continue

    // Don't add duplicates
    if (table.columns.some((c) => c.name === colName)) continue

    const isNotNull = constraints.includes('NOT NULL')
    const hasDefault = constraints.includes('DEFAULT')

    table.columns.push({
      name: colName,
      tsType: sqlTypeToTs(colType),
      nullable: !isNotNull && !hasDefault,
    })
  }
}

// ── Helper: split column definitions respecting parens ──────

function splitColumnDefs(body: string): string[] {
  const parts: string[] = []
  let depth = 0
  let current = ''

  for (const char of body) {
    if (char === '(') depth++
    if (char === ')') depth--
    if (char === ',' && depth === 0) {
      parts.push(current)
      current = ''
    } else {
      current += char
    }
  }
  if (current.trim()) parts.push(current)
  return parts
}

// ── Generate TypeScript ─────────────────────────────────────

function generateTs(tables: Table[]): string {
  const lines: string[] = [
    '// Auto-generated by scripts/generate-db-types.ts — do not edit manually',
    '// Source: migrations/*.sql',
    '',
    '// ── D1 Row Types ──────────────────────────────────────────',
    '// These types map 1:1 to D1 query result rows.',
    '// D1 returns INTEGER as number, TEXT as string, NULL as null.',
    '',
  ]

  for (const table of tables) {
    const typeName = `${toPascalCase(table.name)}Row`
    lines.push(`export interface ${typeName} {`)

    for (const col of table.columns) {
      const nullSuffix = col.nullable ? ' | null' : ''
      lines.push(`  ${col.name}: ${col.tsType}${nullSuffix}`)
    }

    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// ── Main ────────────────────────────────────────────────────

function main(): void {
  // Read all migration files in order
  const files = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql') && /^\d{4}/.test(f))
    .sort()

  let allSql = ''
  for (const file of files) {
    allSql += readFileSync(join(MIGRATIONS_DIR, file), 'utf-8') + '\n'
  }

  // Parse tables from CREATE TABLE
  const tables = parseCreateTable(allSql)
  const tableMap = new Map(tables.map((t) => [t.name, t]))

  // Apply ALTER TABLE ADD COLUMN
  parseAlterAddColumn(allSql, tableMap)

  // Generate output
  const ts = generateTs([...tableMap.values()])
  writeFileSync(OUTPUT_FILE, ts)
  console.log(`✓ Generated ${tableMap.size} table types → ${OUTPUT_FILE}`)
  for (const table of tableMap.values()) {
    console.log(`  ${toPascalCase(table.name)}Row (${table.columns.length} columns)`)
  }
}

main()
